conky.config = {
    alignment = 'top_right',
    background = false,
    font = 'JetBrainsMono Nerd Font:size=10',
    gap_x = 40,
    gap_y = 40,
    own_window = true,
    own_window_type = 'desktop',
    own_window_transparent = true,
    update_interval = 1.0,
    use_xft = true,
}

conky.text = [[
${color #89b4fa}OS:$color Xeno OS
${color #89b4fa}Uptime:$color $uptime
${color #89b4fa}CPU Usage:$color $cpu%
${color #89b4fa}RAM Usage:$color $mem/$memmax
${color #89b4fa}Net Down:$color ${downspeed wlan0}
]]
